baseurl = "/"
languageCode = "en-us"
title = "excelkks"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks] post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4

[params]
    description = "just do it and waiting"
    footer = "&copy; [KKS](https://excelkks.github.io) 2020 | [Github](https://github.com/excelkks) | [E-Mail](mailto:excelkks@hotmail.com)"
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex", "c", "c++", "python", "shell", "markdown"]
    highlightjsTheme = "github"
    show_toc = true
    logo = "/images/favicon/favicon.png"
    favicon = "/images/favicon/favicon.png"
    mathjax = true
    mathjaxEnableSingleDollar = true
[blackfriday]
    smartypants = false
